---
parameters:
    databases:
        mysql:
            host: db.service.dev
            name: stack_hosting
            user: root
            password: root
            type: mysql
        redis:
            host: redis.service.dev
            db: 1
    routines:
        morning: ['good morning', 'telegram', 'whatsapp']
        afternoon: ['good day', 'telegram', 'whatsapp']
        evening: ['good evening', 'telegram', 'whatsapp']
