---
parameters:
    databases:
        mysql:
            host: db
            name: db
            user: db
            password: db
            type: mysql
        redis:
            host: redis
            db: 1
    routines:
        morning: ['hello', 'telegram', 'whatsapp', 'news', 'forex', 'weather', 'email']
        afternoon: ['hello', 'telegram', 'whatsapp', 'forex']
        evening: ['hello', 'telegram', 'whatsapp']
        forex: ['forex']
        weather: ['weather']
        email: ['email']
