---
parameters:
    email:
        user: ''
        password: ''
        host: '' # imap host
        port: 993
        tls: true
        authTimeout: 3000
    weather:
        baseUrl: https://weather.visualcrossing.com/VisualCrossingWebServices/rest/services/timeline/Schiedam?unitGroup=metric&key=API_KEY&contentType=json
        apiKey: VJA6U5777NPFZNS2H6L5V55U7
    databases:
        mysql:
            host: db
            name: db
            user: db
            password: db
            type: mysql
        redis:
            host: redis
            db: 1
    routines:
        morning: ['hello', 'telegram', 'whatsapp', 'news', 'forex', 'weather', 'email']
        afternoon: ['hello', 'telegram', 'whatsapp', 'forex']
        evening: ['hello', 'telegram', 'whatsapp']
        forex: ['forex']
        weather: ['weather']
        email: ['email']
