---
parameters:
    databases:
        mysql:
            host: db.service.dev
            name: stack_hosting
            user: root
            password: root
            type: mysql
        redis:
            host: redis.service.dev
            db: 1
    routines:
        morning: ['hello', 'telegram', 'whatsapp']
        afternoon: ['hello', 'telegram', 'whatsapp']
        evening: ['hello', 'telegram', 'whatsapp']
